default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
repos:
  # enforce commit format
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
