# Project Information
site_name: XAVIER Documentation
site_author: CCBR
site_description: >-
  XAVIER is an open-source, reproducible, and scalable best
  practices pipeline for analyzing Whole Exome DNA-sequencing data.

# Repository
repo_name: CCBR/XAVIER
repo_url: https://github.com/CCBR/XAVIER
edit_uri: https://github.com/CCBR/XAVIER/edit/unified/docs/

# Copyright
copyright: Copyright &copy; 2023-{{ now().year }} CCBR

# Configuration
theme:
  name: readthedocs
  locale: en
  custom_dir: docs/overrides
  #
# Plugins
plugins:
  - search
  - git-revision-date
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/solid/users
      link: http://bioinformatics.cancer.gov
    - icon: fontawesome/brands/github
      link: https://github.com/CCBR
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/nciccbr/repositories
  # version:
  #   provider: mike

extra_css:
  - css/custom.css
extra_javascript:
  - js/custom.js

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page Tree
nav:
  - About: index.md
  - Command Line:
      - xavier run: usage/run.md
      - xavier unlock: usage/unlock.md
      - xavier cache: usage/cache.md
  - Graphical Interface: usage/gui.md
  - Pipeline Details:
      - Overview: pipeline-details/overview.md
      - Methods: pipeline-details/methods.md
      - Tools: pipeline-details/tools.md
      - Settings: pipeline-details/settings.md
      - Output Files: pipeline-details/output.md
  - FAQ:
      - How to contribute: contributing.md
  - License: license.md
