# Project Information
site_name: XAVIER Documentation
site_author: CCBR
site_description: >-
  XAVIER is an open-source, reproducible, and scalable best
  practices pipeline for analyzing Whole Exome DNA-sequencing data. 

# Repository
repo_name: CCBR/XAVIER
repo_url: https://github.com/CCBR/XAVIER
edit_uri: https://github.com/CCBR/XAVIER/edit/unified/docs/

# Extra
extra_css:
  - css/extra.css

# Copyright
copyright: Copyright &copy; 2023 CCBR

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate 
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: assets/icons/doc-book.svg
  favicon: assets/favicon/favicon.ico

# Plugins
plugins:
  - search
  - git-revision-date
  - minify:
      minify_html: true


# Customization
extra:
  social:
    - icon: fontawesome/solid/users
      link: http://bioinformatics.cancer.gov
    - icon: fontawesome/brands/github
      link: https://github.com/CCBR
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/nciccbr/repositories
  version:
    provider: mike


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page Tree
nav:
  - About: index.md
  - Commands: 
    - exome-seek run: usage/run.md
    - exome-seek unlock: usage/unlock.md
    - exome-seek cache: usage/cache.md
  - Pipeline Details: 
    - Overview: pipeline-details/overview.md
    - Methods: pipeline-details/methods.md
    - Tools: pipeline-details/tools.md
    - Settings: pipeline-details/settings.md
    - Output Files: pipeline-details/output.md
  - FAQ:
    - General Questions: faq/questions.md
  - License: license.md
