name: tests

on:
  push:
    branches:
      - master
      - main
      - unified
  pull_request:
    branches-ignore: []

jobs:
  Dry_Run_and_Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://snakemake/snakemake:v6.8.2
    - name: check CLI basics
      run: |
        ./xavier --help
        ./xavier --version
    - name: Tumor-normal FastQ Dry Run
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v6.8.2 \
        /opt2/xavier run --input \
        /opt2/.tests/Sample10_ARK1_S37.R1.fastq.gz /opt2/.tests/Sample10_ARK1_S37.R2.fastq.gz \
        /opt2/.tests/Sample11_ACI_158_S38.R1.fastq.gz /opt2/.tests/Sample11_ACI_158_S38.R2.fastq.gz \
        /opt2/.tests/Sample4_CRL1622_S31.R1.fastq.gz /opt2/.tests/Sample4_CRL1622_S31.R2.fastq.gz \
        --output /opt2/output_tn_fqs --targets /opt2/.tests/Agilent_SSv7_allExons_hg38.bed \
        --pairs /opt2/.tests/pairs.tsv --genome hg38 --mode local --ffpe --cnv --runmode init
        
        docker run -v $PWD:/opt2 snakemake/snakemake:v6.8.2 \
        /opt2/xavier run --input \
        /opt2/.tests/Sample10_ARK1_S37.R1.fastq.gz /opt2/.tests/Sample10_ARK1_S37.R2.fastq.gz \
        /opt2/.tests/Sample11_ACI_158_S38.R1.fastq.gz /opt2/.tests/Sample11_ACI_158_S38.R2.fastq.gz \
        /opt2/.tests/Sample4_CRL1622_S31.R1.fastq.gz /opt2/.tests/Sample4_CRL1622_S31.R2.fastq.gz \
        --output /opt2/output_tn_fqs --targets /opt2/.tests/Agilent_SSv7_allExons_hg38.bed \
        --pairs /opt2/.tests/pairs.tsv --genome hg38 --mode local --ffpe --cnv --runmode dryrun
        
    - name: Tumor-only FastQ Dry Run
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v6.8.2 \
        /opt2/xavier run --input \
        /opt2/.tests/Sample10_ARK1_S37.R1.fastq.gz /opt2/.tests/Sample10_ARK1_S37.R2.fastq.gz \
        /opt2/.tests/Sample11_ACI_158_S38.R1.fastq.gz /opt2/.tests/Sample11_ACI_158_S38.R2.fastq.gz \
        /opt2/.tests/Sample4_CRL1622_S31.R1.fastq.gz /opt2/.tests/Sample4_CRL1622_S31.R2.fastq.gz \
        --output /opt2/output_tonly_fqs --targets /opt2/.tests/Agilent_SSv7_allExons_hg38.bed \
        --genome hg38 --mode local --ffpe --runmode init
        
        docker run -v $PWD:/opt2 snakemake/snakemake:v6.8.2 \
        /opt2/xavier run --input \
        /opt2/.tests/Sample10_ARK1_S37.R1.fastq.gz /opt2/.tests/Sample10_ARK1_S37.R2.fastq.gz \
        /opt2/.tests/Sample11_ACI_158_S38.R1.fastq.gz /opt2/.tests/Sample11_ACI_158_S38.R2.fastq.gz \
        /opt2/.tests/Sample4_CRL1622_S31.R1.fastq.gz /opt2/.tests/Sample4_CRL1622_S31.R2.fastq.gz \
        --output /opt2/output_tonly_fqs --targets /opt2/.tests/Agilent_SSv7_allExons_hg38.bed \
        --genome hg38 --mode local --ffpe --runmode dryrun
        
    - name: Tumor-normal BAM Dry Run
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v6.8.2 \
        /opt2/xavier run --input \
        /opt2/.tests/Sample10_ARK1_S37.recal.bam \
        /opt2/.tests/Sample11_ACI_158_S38.recal.bam \
        /opt2/.tests/Sample4_CRL1622_S31.recal.bam \
        --output /opt2/output_tn_bams --targets /opt2/.tests/Agilent_SSv7_allExons_hg38.bed \
        --pairs /opt2/.tests/pairs.tsv --genome hg38 --mode local --ffpe --cnv --runmode init
        
        docker run -v $PWD:/opt2 snakemake/snakemake:v6.8.2 \
        /opt2/xavier run --input \
        /opt2/.tests/Sample10_ARK1_S37.recal.bam \
        /opt2/.tests/Sample11_ACI_158_S38.recal.bam \
        /opt2/.tests/Sample4_CRL1622_S31.recal.bam \
        --output /opt2/output_tn_bams --targets /opt2/.tests/Agilent_SSv7_allExons_hg38.bed \
        --pairs /opt2/.tests/pairs.tsv --genome hg38 --mode local --ffpe --cnv --runmode dryrun
        
    - name: Tumor-only BAM Dry Run
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v6.8.2 \
        /opt2/xavier run --input \
        /opt2/.tests/Sample10_ARK1_S37.recal.bam \
        /opt2/.tests/Sample11_ACI_158_S38.recal.bam \
        /opt2/.tests/Sample4_CRL1622_S31.recal.bam \
        --output /opt2/output_tonly_bams --targets /opt2/.tests/Agilent_SSv7_allExons_hg38.bed \
        --genome hg38 --mode local --ffpe --runmode init
        
        docker run -v $PWD:/opt2 snakemake/snakemake:v6.8.2 \
        /opt2/xavier run --input \
        /opt2/.tests/Sample10_ARK1_S37.recal.bam \
        /opt2/.tests/Sample11_ACI_158_S38.recal.bam \
        /opt2/.tests/Sample4_CRL1622_S31.recal.bam \
        --output /opt2/output_tonly_bams --targets /opt2/.tests/Agilent_SSv7_allExons_hg38.bed \
        --genome hg38 --mode local --ffpe --runmode dryrun
        
    - name: Lint Workflow
      continue-on-error: true
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 snakemake --lint -s /opt2/output/workflow/Snakefile -d /opt2/output_tn_fqs || \
        echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'
